### ISSUE TITLE
[Fx Tab] -> [Servo]

### ISSUE THREAD

**Issue by jsantell** [joewalker/devtools.html#4]
Bonus points if it runs _in_ servo, but debugging a servo tab is sufficient.

**Comment by jsantell** [comment]
Needs #9

**Comment by bgrins** [comment]
Tried running it in a servo tab and get a crash.. Here's the log leading up to it:

```
ERROR:js::rust: Error at file:///devtoolsweb/built/toolbox.js:2991:5: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

Cc sham for
@mozilla.org/xre/app-info;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/widget/clipboardhelper;1
Cc sham for
@mozilla.org/content/style-sheet-service;1
Cc sham for
@mozilla.org/network/io-service;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/xre/app-info;1
generateQI is a sham
,
Cc sham for
@mozilla.org/serviceworkers/manager;1
generateQI is a sham

generateQI is a sham

generateQI is a sham
,
No cached boolean pref for devtools.debugger.ui.variables-sorting-enabled
Cc sham for
@mozilla.org/xmlextras/domparser;1
Cc sham for
@mozilla.org/io-util;1
CC sham for
@mozilla.org/scriptableinputstream;1
nsIScriptableInputStream
init
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1
Cc sham for
@mozilla.org/inspector/dom-utils;1

TypeError: this.closeButton is null
Open finished
thread 'ScriptTask PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:367
stack backtrace:
   1:        0x10c15ffc8 - sys::backtrace::tracing::imp::write::h3ed615ef3cda9b6b7It
   2:        0x10c16210f - panicking::log_panic::_<closure>::closure.40650
   3:        0x10c161bb2 - panicking::log_panic::hdfd4a4ec7b55d6a5MAx
   4:        0x10c14d0a6 - sys_common::unwind::begin_unwind_inner::h2f70decd24e7a2917Ls
   5:        0x10c14d48e - sys_common::unwind::begin_unwind_fmt::h29da0d611b24747ddLs
   6:        0x10c15f5e7 - rust_begin_unwind
   7:        0x10c184770 - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:        0x10c184a6c - panicking::panic::h72b18290823e7468sEK
   9:        0x10aa67932 - option::_<impl>::unwrap::unwrap::h14579938482901389561
  10:        0x10aa669e0 - timers::_<impl>::fire_timer::h18297823297380353439
  11:        0x10aa664fd - dom::window::_<impl>::handle_fire_timer::h8ebccab12a69b10bLsU
  12:        0x10ab5c642 - script_task::_<impl>::handle_timer_event::hd1b2e1519671cc6fJ8Y
  13:        0x10ab5a5db - script_task::_<impl>::handle_msgs::_<closure>::closure.160862
  14:        0x10ab5a122 - script_task::_<impl>::profile_event::h14308424675409408775
  15:        0x10ab2cc69 - script_task::_<impl>::handle_msgs::haf9688c31dd02308QTY
  16:        0x10aad7840 - script_task::_<impl>::start::h6230160b93a5ff92GTY
  17:        0x10aad77f4 - script_task::_<impl>::create::_<closure>::_<closure>::closure.159576
  18:        0x10aad7560 - mem::_<impl>::run_with_memory_reporting::run_with_memory_reporting::h11915197458443459605
  19:        0x10aac1bef - script_task::_<impl>::create::_<closure>::closure.158954
  20:        0x10aac0fc7 - util::task::spawn_named_with_send_on_failure::_<closure>::closure.158941
  21:        0x10aac09b3 - std::thread::_<impl>::spawn::_<closure>::_<closure>::closure.158930
  22:        0x10aac0928 - sys_common::unwind::try::try_fn::try_fn::h11089067699197339792
  23:        0x10c15f408 - __rust_try
  24:        0x10c15c50e - sys_common::unwind::try::inner_try::hd7e4f8fc422767d2FIs
  25:        0x10aac0865 - sys_common::unwind::try::try::h14056457263645219478
  26:        0x10aac069e - std::thread::_<impl>::spawn::_<closure>::closure.158927
  27:        0x10aac11e7 - boxed::_<impl>::call_box::call_box::h607922269286226986
  28:        0x10c16139d - sys::thread::_<impl>::new::thread_start::ha2c46efb1706c462jVw
  29:     0x7fff8c2e9059 - _pthread_body
  30:     0x7fff8c2e8fd6 - _pthread_start
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore/option.rs:335
stack backtrace:
```

**Comment by bgrins** [comment]
Got this running with servo as the backend via  `./mach run --devtools 6080 https://google.com` and the inspector kind of sort of works.  The markup tree is displayed but no rule view, and edits don't seem to work.  But that could well be limitations of the implemented methods on the backend, I haven't checked yet to see how the same thing works with a web ide connection and a normal toolbox

**Comment by bgrins** [comment]
Turns out the crash in https://github.com/joewalker/devtools.html/issues/4#issuecomment-161012962 was due to a bad pull, updating servo and rebuilding fixed it
